(function(root){
'use strict';
const thresholds=[0,500,1000,1750,2500,3250,4000];
const stats=['INT','BUILD','FOCUS','END','LEVERAGE'];
function day(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function fresh(){return {version:1,entries:[],custom:[],purchases:[],equipped:'sage',mode:'normal',position:{x:555,y:380},seenIntro:false};}
function total(s){return s.entries.reduce((n,e)=>n+e.xp,0);}
function level(xp){for(let i=0;i<thresholds.length-1;i++)if(xp<thresholds[i+1])return i+1;return 7+Math.floor((xp-4000)/750);}
function bounds(xp){let l=level(xp);return {level:l,start:l<=7?thresholds[l-1]:4000+(l-7)*750,next:l<7?thresholds[l]:4000+(l-6)*750};}
function coins(s){return s.entries.reduce((n,e)=>n+Math.floor(e.xp/10),0)-s.purchases.reduce((n,e)=>n+e.cost,0);}
function statTotals(s){return Object.fromEntries(stats.map(k=>[k,s.entries.filter(e=>e.stat===k).reduce((n,e)=>n+e.xp,0)]));}
function key(q,date=day()){return q.repeat?q.id+':'+date:q.id;}
function completed(s,q,date=day()){return s.entries.some(e=>e.key===key(q,date));}
function award(s,q,note,date=day()){if(completed(s,q,date))throw Error('This quest has already been claimed.');if(!note.trim())throw Error('Add a short completion note first.');if(level(total(s))<(q.unlock||1))throw Error('This area is still locked.');s.entries.push({key:key(q,date),questId:q.id,title:q.title,stat:q.stat,xp:q.xp,note:note.trim().slice(0,2000),date,region:q.region,boss:!!q.boss,...(q.bot?{bot:String(q.bot).slice(0,40)}:{})});return s;}
function validate(s){if(!s||s.version!==1||!Array.isArray(s.entries)||s.entries.length>10000||!Array.isArray(s.custom)||s.custom.length>500||!Array.isArray(s.purchases))throw Error('That file is not a valid game save.');const keys=new Set();for(const e of s.entries){if(!e||typeof e.key!=='string'||keys.has(e.key)||!Number.isInteger(e.xp)||e.xp<0||e.xp>250||!stats.includes(e.stat)||typeof e.title!=='string'||typeof e.note!=='string'||e.bot!==undefined&&(typeof e.bot!=='string'||e.bot.length>40)||!/^\d{4}-\d{2}-\d{2}$/.test(e.date))throw Error('The save contains an invalid quest entry.');keys.add(e.key);}for(const q of s.custom)if(!q||typeof q.id!=='string'||!q.id.startsWith('custom-')||typeof q.title!=='string'||!stats.includes(q.stat)||![20,40,60,100,250].includes(q.xp)||!['camp','forge','citadel','grove','tower','temple','lab','summit'].includes(q.region)||!Number.isInteger(q.unlock)||q.unlock<1||q.unlock>5||typeof q.detail!=='string'||typeof q.repeat!=='boolean')throw Error('The save contains an invalid custom quest.');const purchased=new Set();for(const p of s.purchases){if(!p||!['ember','midnight','rose'].includes(p.id)||purchased.has(p.id)||p.cost!==({ember:30,midnight:60,rose:90})[p.id])throw Error('Invalid reward purchase.');purchased.add(p.id);}if(coins(s)<0)throw Error('Invalid coin balance.');if(!['sage','ember','midnight','rose'].includes(s.equipped)||s.equipped!=='sage'&&!purchased.has(s.equipped))throw Error('Invalid equipped cloak.');if(!['normal','recovery'].includes(s.mode))throw Error('Invalid play mode.');if(!s.position||!Number.isFinite(s.position.x)||!Number.isFinite(s.position.y)||s.position.x<40||s.position.x>1060||s.position.y<40||s.position.y>690)s.position={x:555,y:380};return s;}
const api={day,fresh,total,level,bounds,coins,statTotals,key,completed,award,validate,stats};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.GameEngine=api;
})(typeof window!=='undefined'?window:globalThis);
